name: secrets

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  scan-for-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
      - uses: gacts/gitleaks@03e7105de6e27d619be467b70e6d2c9657780d9b # v1.2.3
        with:
          config-path: .github/.gitleaks.toml
